### ISSUE TITLE
fix activities link

### ISSUE THREAD

**Issue by kareem-ib** [kangarang/tcr-ui#105] opened 2018-07-19 16:45 UTC
the activities link will not open up when clicked

**Comment by Hu4F00d** [comment] 2018-07-24 22:03
The problem is not the link, there seems to be a problem with the SimpleTabs component: 
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `SimpleTabs`.
```
It was working with a previous commit, so I'm checking what changed.

**Comment by kangarang** [comment] 2018-07-25 00:16
@Hu4F00d @kareem-ib, thanks guys. i should have removed the Activities route a while back, as it hasn't been functional for a while :/ that part of the app was left stale while a new design was in progress. i'm gonna be pushing some pretty big changes in a day or so, along with new wireframes to help guide us going forward. please don't spend any more time debugging the Activities page!

**Comment by kangarang** [comment] 2018-07-25 16:39
closing, please see latest changes

**Closed by kangarang** 2018-07-25 16:39 UTC
